{
	"document": {
		"aggregate_severity": {
			"namespace": "https://access.redhat.com/security/updates/classification/",
			"text": "moderate"
		},
		"category": "csaf_vex",
		"csaf_version": "2.0",
		"distribution": {
			"text": "Copyright Â© Red Hat, Inc. All rights reserved.",
			"tlp": {
				"label": "WHITE",
				"url": "https://www.first.org/tlp/"
			}
		},
		"lang": "en",
		"notes": [
			{
				"category": "legal_disclaimer",
				"text": "This content is licensed under the Creative Commons Attribution 4.0 International License (https://creativecommons.org/licenses/by/4.0/). If you distribute this content, or a modified version of it, you must provide attribution to Red Hat Inc. and provide a link to the original.",
				"title": "Terms of Use"
			}
		],
		"publisher": {
			"category": "vendor",
			"contact_details": "https://access.redhat.com/security/team/contact/",
			"issuing_authority": "Red Hat Product Security is responsible for vulnerability handling across all Red Hat offerings.",
			"name": "Red Hat Product Security",
			"namespace": "https://www.redhat.com"
		},
		"references": [
			{
				"category": "self",
				"summary": "Canonical URL",
				"url": "https://access.redhat.com/security/data/csaf/beta/vex/2023/cve-2023-27043.json"
			}
		],
		"title": "python: Parsing errors in email/_parseaddr.py lead to incorrect value in email address part of tuple",
		"tracking": {
			"current_release_date": "2023-10-05T17:31:34+00:00",
			"generator": {
				"date": "2023-11-20T11:23:54+00:00",
				"engine": {
					"name": "Red Hat SDEngine",
					"version": "3.24.0"
				}
			},
			"id": "CVE-2023-27043",
			"initial_release_date": "2023-04-19T00:00:00+00:00",
			"revision_history": [
				{
					"date": "2023-04-19T00:00:00+00:00",
					"number": "1",
					"summary": "Initial version"
				},
				{
					"date": "2023-10-05T17:31:34+00:00",
					"number": "2",
					"summary": "Current version"
				}
			],
			"status": "final",
			"version": "1"
		}
	},
	"product_tree": {
		"branches": [
			{
				"branches": [
					{
						"category": "product_name",
						"name": "Red Hat Enterprise Linux 6",
						"product": {
							"name": "Red Hat Enterprise Linux 6",
							"product_id": "red_hat_enterprise_linux_6",
							"product_identification_helper": {
								"cpe": "cpe:/o:redhat:enterprise_linux:6"
							}
						}
					},
					{
						"category": "product_name",
						"name": "Red Hat Enterprise Linux 7",
						"product": {
							"name": "Red Hat Enterprise Linux 7",
							"product_id": "red_hat_enterprise_linux_7",
							"product_identification_helper": {
								"cpe": "cpe:/o:redhat:enterprise_linux:7"
							}
						}
					},
					{
						"category": "product_name",
						"name": "Red Hat Enterprise Linux 8",
						"product": {
							"name": "Red Hat Enterprise Linux 8",
							"product_id": "red_hat_enterprise_linux_8",
							"product_identification_helper": {
								"cpe": "cpe:/o:redhat:enterprise_linux:8"
							}
						}
					},
					{
						"category": "product_name",
						"name": "Red Hat Enterprise Linux 9",
						"product": {
							"name": "Red Hat Enterprise Linux 9",
							"product_id": "red_hat_enterprise_linux_9",
							"product_identification_helper": {
								"cpe": "cpe:/o:redhat:enterprise_linux:9"
							}
						}
					},
					{
						"category": "product_name",
						"name": "Red Hat Software Collections",
						"product": {
							"name": "Red Hat Software Collections",
							"product_id": "red_hat_software_collections",
							"product_identification_helper": {
								"cpe": "cpe:/a:redhat:rhel_software_collections:3"
							}
						}
					},
					{
						"category": "product_version",
						"name": "python",
						"product": {
							"name": "python",
							"product_id": "python"
						}
					},
					{
						"category": "product_version",
						"name": "python3",
						"product": {
							"name": "python3",
							"product_id": "python3"
						}
					},
					{
						"category": "product_version",
						"name": "python27:2.7/python2",
						"product": {
							"name": "python27:2.7/python2",
							"product_id": "python27:2.7/python2"
						}
					},
					{
						"category": "product_version",
						"name": "python3.11",
						"product": {
							"name": "python3.11",
							"product_id": "python3.11"
						}
					},
					{
						"category": "product_version",
						"name": "python36:3.6/python36",
						"product": {
							"name": "python36:3.6/python36",
							"product_id": "python36:3.6/python36"
						}
					},
					{
						"category": "product_version",
						"name": "python38:3.8/python38",
						"product": {
							"name": "python38:3.8/python38",
							"product_id": "python38:3.8/python38"
						}
					},
					{
						"category": "product_version",
						"name": "python39:3.9/python39",
						"product": {
							"name": "python39:3.9/python39",
							"product_id": "python39:3.9/python39"
						}
					},
					{
						"category": "product_version",
						"name": "python3.9",
						"product": {
							"name": "python3.9",
							"product_id": "python3.9"
						}
					},
					{
						"category": "product_version",
						"name": "rh-python38-python",
						"product": {
							"name": "rh-python38-python",
							"product_id": "rh-python38-python"
						}
					}
				],
				"category": "vendor",
				"name": "Red Hat"
			}
		],
		"relationships": [
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python as a component of Red Hat Enterprise Linux 6",
					"product_id": "red_hat_enterprise_linux_6:python"
				},
				"product_reference": "python",
				"relates_to_product_reference": "red_hat_enterprise_linux_6"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python as a component of Red Hat Enterprise Linux 7",
					"product_id": "red_hat_enterprise_linux_7:python"
				},
				"product_reference": "python",
				"relates_to_product_reference": "red_hat_enterprise_linux_7"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python3 as a component of Red Hat Enterprise Linux 7",
					"product_id": "red_hat_enterprise_linux_7:python3"
				},
				"product_reference": "python3",
				"relates_to_product_reference": "red_hat_enterprise_linux_7"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python27:2.7/python2 as a component of Red Hat Enterprise Linux 8",
					"product_id": "red_hat_enterprise_linux_8:python27:2.7/python2"
				},
				"product_reference": "python27:2.7/python2",
				"relates_to_product_reference": "red_hat_enterprise_linux_8"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python3 as a component of Red Hat Enterprise Linux 8",
					"product_id": "red_hat_enterprise_linux_8:python3"
				},
				"product_reference": "python3",
				"relates_to_product_reference": "red_hat_enterprise_linux_8"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python3.11 as a component of Red Hat Enterprise Linux 8",
					"product_id": "red_hat_enterprise_linux_8:python3.11"
				},
				"product_reference": "python3.11",
				"relates_to_product_reference": "red_hat_enterprise_linux_8"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python36:3.6/python36 as a component of Red Hat Enterprise Linux 8",
					"product_id": "red_hat_enterprise_linux_8:python36:3.6/python36"
				},
				"product_reference": "python36:3.6/python36",
				"relates_to_product_reference": "red_hat_enterprise_linux_8"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python38:3.8/python38 as a component of Red Hat Enterprise Linux 8",
					"product_id": "red_hat_enterprise_linux_8:python38:3.8/python38"
				},
				"product_reference": "python38:3.8/python38",
				"relates_to_product_reference": "red_hat_enterprise_linux_8"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python39:3.9/python39 as a component of Red Hat Enterprise Linux 8",
					"product_id": "red_hat_enterprise_linux_8:python39:3.9/python39"
				},
				"product_reference": "python39:3.9/python39",
				"relates_to_product_reference": "red_hat_enterprise_linux_8"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python3.11 as a component of Red Hat Enterprise Linux 9",
					"product_id": "red_hat_enterprise_linux_9:python3.11"
				},
				"product_reference": "python3.11",
				"relates_to_product_reference": "red_hat_enterprise_linux_9"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python3.9 as a component of Red Hat Enterprise Linux 9",
					"product_id": "red_hat_enterprise_linux_9:python3.9"
				},
				"product_reference": "python3.9",
				"relates_to_product_reference": "red_hat_enterprise_linux_9"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "rh-python38-python as a component of Red Hat Software Collections",
					"product_id": "red_hat_software_collections:rh-python38-python"
				},
				"product_reference": "rh-python38-python",
				"relates_to_product_reference": "red_hat_software_collections"
			}
		]
	},
	"vulnerabilities": [
		{
			"cve": "CVE-2023-27043",
			"cwe": {
				"id": "CWE-20",
				"name": "Improper Input Validation"
			},
			"discovery_date": "2023-05-08T00:00:00+00:00",
			"flags": [
				{
					"label": "vulnerable_code_not_present",
					"product_ids": [
						"red_hat_enterprise_linux_8:python36:3.6/python36"
					]
				}
			],
			"ids": [
				{
					"system_name": "Red Hat Bugzilla ID",
					"text": "2196183"
				}
			],
			"notes": [
				{
					"category": "description",
					"text": "The email module of Python through 3.11.3 incorrectly parses e-mail addresses that contain a special character. The wrong portion of an RFC2822 header is identified as the value of the addr-spec. In some applications, an attacker can bypass a protection mechanism in which application access is granted only after verifying receipt of e-mail to a specific domain (e.g., only @company.example.com addresses may be used for signup). This occurs in email/_parseaddr.py in recent versions of Python.",
					"title": "Vulnerability description"
				},
				{
					"category": "summary",
					"text": "python: Parsing errors in email/_parseaddr.py lead to incorrect value in email address part of tuple",
					"title": "Vulnerability summary"
				},
				{
					"category": "other",
					"text": "Versions of python36:3.6/python36 as shipped with Red Hat Enterprise Linux 8 are marked as 'Not affected' as they just provide \"symlinks\" to the main python3 component, which provides the actual interpreter of the Python programming language.",
					"title": "Statement"
				},
				{
					"category": "general",
					"text": "The CVSS score(s) listed for this vulnerability do not reflect the associated product's status, and are included for informational purposes to better understand the severity of this vulnerability.",
					"title": "CVSS score applicability"
				}
			],
			"product_status": {
				"known_affected": [
					"red_hat_enterprise_linux_6:python",
					"red_hat_enterprise_linux_7:python",
					"red_hat_enterprise_linux_7:python3",
					"red_hat_enterprise_linux_8:python27:2.7/python2",
					"red_hat_enterprise_linux_8:python3",
					"red_hat_enterprise_linux_8:python3.11",
					"red_hat_enterprise_linux_8:python38:3.8/python38",
					"red_hat_enterprise_linux_8:python39:3.9/python39",
					"red_hat_enterprise_linux_9:python3.11",
					"red_hat_enterprise_linux_9:python3.9",
					"red_hat_software_collections:rh-python38-python"
				],
				"known_not_affected": [
					"red_hat_enterprise_linux_8:python36:3.6/python36"
				]
			},
			"references": [
				{
					"category": "self",
					"summary": "Canonical URL",
					"url": "https://access.redhat.com/security/cve/CVE-2023-27043"
				},
				{
					"category": "external",
					"summary": "RHBZ#2196183",
					"url": "https://bugzilla.redhat.com/show_bug.cgi?id=2196183"
				},
				{
					"category": "external",
					"summary": "https://www.cve.org/CVERecord?id=CVE-2023-27043",
					"url": "https://www.cve.org/CVERecord?id=CVE-2023-27043"
				},
				{
					"category": "external",
					"summary": "https://nvd.nist.gov/vuln/detail/CVE-2023-27043",
					"url": "https://nvd.nist.gov/vuln/detail/CVE-2023-27043"
				}
			],
			"release_date": "2023-04-19T00:00:00+00:00",
			"remediations": [
				{
					"category": "no_fix_planned",
					"details": "Out of support scope",
					"product_ids": [
						"red_hat_enterprise_linux_6:python",
						"red_hat_enterprise_linux_7:python",
						"red_hat_enterprise_linux_7:python3"
					]
				},
				{
					"category": "no_fix_planned",
					"details": "Will not fix",
					"product_ids": [
						"red_hat_enterprise_linux_8:python27:2.7/python2",
						"red_hat_enterprise_linux_9:python3.11",
						"red_hat_software_collections:rh-python38-python"
					]
				},
				{
					"category": "none_available",
					"details": "Affected",
					"product_ids": [
						"red_hat_enterprise_linux_8:python3",
						"red_hat_enterprise_linux_8:python3.11",
						"red_hat_enterprise_linux_8:python38:3.8/python38",
						"red_hat_enterprise_linux_8:python39:3.9/python39",
						"red_hat_enterprise_linux_9:python3.9"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"attackComplexity": "LOW",
						"attackVector": "NETWORK",
						"availabilityImpact": "NONE",
						"baseScore": 5.3,
						"baseSeverity": "MEDIUM",
						"confidentialityImpact": "NONE",
						"integrityImpact": "LOW",
						"privilegesRequired": "NONE",
						"scope": "UNCHANGED",
						"userInteraction": "NONE",
						"vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N",
						"version": "3.1"
					},
					"products": [
						"red_hat_enterprise_linux_6:python",
						"red_hat_enterprise_linux_7:python",
						"red_hat_enterprise_linux_7:python3",
						"red_hat_enterprise_linux_8:python27:2.7/python2",
						"red_hat_enterprise_linux_8:python3",
						"red_hat_enterprise_linux_8:python3.11",
						"red_hat_enterprise_linux_8:python38:3.8/python38",
						"red_hat_enterprise_linux_8:python39:3.9/python39",
						"red_hat_enterprise_linux_9:python3.11",
						"red_hat_enterprise_linux_9:python3.9",
						"red_hat_software_collections:rh-python38-python"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"details": "Moderate",
					"product_ids": [
						"red_hat_enterprise_linux_6:python",
						"red_hat_enterprise_linux_7:python",
						"red_hat_enterprise_linux_7:python3",
						"red_hat_enterprise_linux_8:python27:2.7/python2",
						"red_hat_enterprise_linux_8:python3",
						"red_hat_enterprise_linux_8:python3.11",
						"red_hat_enterprise_linux_8:python38:3.8/python38",
						"red_hat_enterprise_linux_8:python39:3.9/python39",
						"red_hat_enterprise_linux_9:python3.11",
						"red_hat_enterprise_linux_9:python3.9",
						"red_hat_software_collections:rh-python38-python"
					]
				}
			],
			"title": "python: Parsing errors in email/_parseaddr.py lead to incorrect value in email address part of tuple"
		}
	]
}
