{
	"document": {
		"aggregate_severity": {
			"namespace": "https://access.redhat.com/security/updates/classification/",
			"text": "moderate"
		},
		"category": "csaf_vex",
		"csaf_version": "2.0",
		"distribution": {
			"text": "Copyright Â© Red Hat, Inc. All rights reserved.",
			"tlp": {
				"label": "WHITE",
				"url": "https://www.first.org/tlp/"
			}
		},
		"lang": "en",
		"notes": [
			{
				"category": "legal_disclaimer",
				"text": "This content is licensed under the Creative Commons Attribution 4.0 International License (https://creativecommons.org/licenses/by/4.0/). If you distribute this content, or a modified version of it, you must provide attribution to Red Hat Inc. and provide a link to the original.",
				"title": "Terms of Use"
			}
		],
		"publisher": {
			"category": "vendor",
			"contact_details": "https://access.redhat.com/security/team/contact/",
			"issuing_authority": "Red Hat Product Security is responsible for vulnerability handling across all Red Hat offerings.",
			"name": "Red Hat Product Security",
			"namespace": "https://www.redhat.com"
		},
		"references": [
			{
				"category": "self",
				"summary": "Canonical URL",
				"url": "https://access.redhat.com/security/data/csaf/beta/vex/2024/cve-2024-28102.json"
			}
		],
		"title": "python-jwcrypto: malicious JWE token can cause denial of service",
		"tracking": {
			"current_release_date": "2024-03-11T13:38:50+00:00",
			"generator": {
				"date": "2024-03-11T13:38:50+00:00",
				"engine": {
					"name": "Red Hat SDEngine",
					"version": "3.27.1"
				}
			},
			"id": "CVE-2024-28102",
			"initial_release_date": "2024-03-08T00:00:00+00:00",
			"revision_history": [
				{
					"date": "2024-03-08T00:00:00+00:00",
					"number": "1",
					"summary": "Initial version"
				},
				{
					"date": "2024-03-11T13:20:04+00:00",
					"number": "2",
					"summary": "Current version"
				},
				{
					"date": "2024-03-11T13:38:50+00:00",
					"number": "3",
					"summary": "Last generated version"
				}
			],
			"status": "final",
			"version": "3"
		}
	},
	"product_tree": {
		"branches": [
			{
				"branches": [
					{
						"category": "product_name",
						"name": "Red Hat Ansible Automation Platform 2",
						"product": {
							"name": "Red Hat Ansible Automation Platform 2",
							"product_id": "red_hat_ansible_automation_platform_2",
							"product_identification_helper": {
								"cpe": "cpe:/a:redhat:ansible_automation_platform:2"
							}
						}
					},
					{
						"category": "product_name",
						"name": "Red Hat Enterprise Linux 7",
						"product": {
							"name": "Red Hat Enterprise Linux 7",
							"product_id": "red_hat_enterprise_linux_7",
							"product_identification_helper": {
								"cpe": "cpe:/o:redhat:enterprise_linux:7"
							}
						}
					},
					{
						"category": "product_name",
						"name": "Red Hat Enterprise Linux 8",
						"product": {
							"name": "Red Hat Enterprise Linux 8",
							"product_id": "red_hat_enterprise_linux_8",
							"product_identification_helper": {
								"cpe": "cpe:/o:redhat:enterprise_linux:8"
							}
						}
					},
					{
						"category": "product_name",
						"name": "Red Hat Enterprise Linux 9",
						"product": {
							"name": "Red Hat Enterprise Linux 9",
							"product_id": "red_hat_enterprise_linux_9",
							"product_identification_helper": {
								"cpe": "cpe:/o:redhat:enterprise_linux:9"
							}
						}
					},
					{
						"category": "product_version",
						"name": "automation-controller",
						"product": {
							"name": "automation-controller",
							"product_id": "automation-controller"
						}
					},
					{
						"category": "product_version",
						"name": "python-jwcrypto",
						"product": {
							"name": "python-jwcrypto",
							"product_id": "python-jwcrypto"
						}
					},
					{
						"category": "product_version",
						"name": "idm:client/python-jwcrypto",
						"product": {
							"name": "idm:client/python-jwcrypto",
							"product_id": "idm:client/python-jwcrypto"
						}
					},
					{
						"category": "product_version",
						"name": "idm:DL1/python-jwcrypto",
						"product": {
							"name": "idm:DL1/python-jwcrypto",
							"product_id": "idm:DL1/python-jwcrypto"
						}
					}
				],
				"category": "vendor",
				"name": "Red Hat"
			}
		],
		"relationships": [
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "automation-controller as a component of Red Hat Ansible Automation Platform 2",
					"product_id": "red_hat_ansible_automation_platform_2:automation-controller"
				},
				"product_reference": "automation-controller",
				"relates_to_product_reference": "red_hat_ansible_automation_platform_2"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python-jwcrypto as a component of Red Hat Enterprise Linux 7",
					"product_id": "red_hat_enterprise_linux_7:python-jwcrypto"
				},
				"product_reference": "python-jwcrypto",
				"relates_to_product_reference": "red_hat_enterprise_linux_7"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "idm:DL1/python-jwcrypto as a component of Red Hat Enterprise Linux 8",
					"product_id": "red_hat_enterprise_linux_8:idm:DL1/python-jwcrypto"
				},
				"product_reference": "idm:DL1/python-jwcrypto",
				"relates_to_product_reference": "red_hat_enterprise_linux_8"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "idm:client/python-jwcrypto as a component of Red Hat Enterprise Linux 8",
					"product_id": "red_hat_enterprise_linux_8:idm:client/python-jwcrypto"
				},
				"product_reference": "idm:client/python-jwcrypto",
				"relates_to_product_reference": "red_hat_enterprise_linux_8"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python-jwcrypto as a component of Red Hat Enterprise Linux 9",
					"product_id": "red_hat_enterprise_linux_9:python-jwcrypto"
				},
				"product_reference": "python-jwcrypto",
				"relates_to_product_reference": "red_hat_enterprise_linux_9"
			}
		]
	},
	"vulnerabilities": [
		{
			"cve": "CVE-2024-28102",
			"cwe": {
				"id": "CWE-400",
				"name": "Uncontrolled Resource Consumption"
			},
			"discovery_date": "2024-03-10T00:00:00+00:00",
			"ids": [
				{
					"system_name": "Red Hat Bugzilla ID",
					"text": "2268758"
				}
			],
			"notes": [
				{
					"category": "description",
					"text": "An uncontrolled resource consumption vulnerability was found in python-jwcrypto. If a malicious JWE token with a high compression ratio is passed to the server, the server will consume a lot of memory and processing time, leading to a denial of service.",
					"title": "Vulnerability description"
				},
				{
					"category": "summary",
					"text": "python-jwcrypto: malicious JWE token can cause denial of service",
					"title": "Vulnerability summary"
				},
				{
					"category": "general",
					"text": "The CVSS score(s) listed for this vulnerability do not reflect the associated product's status, and are included for informational purposes to better understand the severity of this vulnerability.",
					"title": "CVSS score applicability"
				}
			],
			"product_status": {
				"known_affected": [
					"red_hat_enterprise_linux_7:python-jwcrypto"
				],
				"under_investigation": [
					"red_hat_ansible_automation_platform_2:automation-controller",
					"red_hat_enterprise_linux_8:idm:DL1/python-jwcrypto",
					"red_hat_enterprise_linux_8:idm:client/python-jwcrypto",
					"red_hat_enterprise_linux_9:python-jwcrypto"
				]
			},
			"references": [
				{
					"category": "self",
					"summary": "Canonical URL",
					"url": "https://access.redhat.com/security/cve/CVE-2024-28102"
				},
				{
					"category": "external",
					"summary": "RHBZ#2268758",
					"url": "https://bugzilla.redhat.com/show_bug.cgi?id=2268758"
				},
				{
					"category": "external",
					"summary": "https://www.cve.org/CVERecord?id=CVE-2024-28102",
					"url": "https://www.cve.org/CVERecord?id=CVE-2024-28102"
				},
				{
					"category": "external",
					"summary": "https://nvd.nist.gov/vuln/detail/CVE-2024-28102",
					"url": "https://nvd.nist.gov/vuln/detail/CVE-2024-28102"
				},
				{
					"category": "external",
					"summary": "https://github.com/latchset/jwcrypto/commit/90477a3b6e73da69740e00b8161f53fea19b831f",
					"url": "https://github.com/latchset/jwcrypto/commit/90477a3b6e73da69740e00b8161f53fea19b831f"
				},
				{
					"category": "external",
					"summary": "https://github.com/latchset/jwcrypto/security/advisories/GHSA-j857-7rvv-vj97",
					"url": "https://github.com/latchset/jwcrypto/security/advisories/GHSA-j857-7rvv-vj97"
				}
			],
			"release_date": "2024-03-08T00:00:00+00:00",
			"remediations": [
				{
					"category": "no_fix_planned",
					"details": "Out of support scope",
					"product_ids": [
						"red_hat_enterprise_linux_7:python-jwcrypto"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"attackComplexity": "LOW",
						"attackVector": "NETWORK",
						"availabilityImpact": "HIGH",
						"baseScore": 6.8,
						"baseSeverity": "MEDIUM",
						"confidentialityImpact": "NONE",
						"integrityImpact": "NONE",
						"privilegesRequired": "HIGH",
						"scope": "CHANGED",
						"userInteraction": "NONE",
						"vectorString": "CVSS:3.1/AV:N/AC:L/PR:H/UI:N/S:C/C:N/I:N/A:H",
						"version": "3.1"
					},
					"products": [
						"red_hat_ansible_automation_platform_2:automation-controller",
						"red_hat_enterprise_linux_7:python-jwcrypto",
						"red_hat_enterprise_linux_8:idm:DL1/python-jwcrypto",
						"red_hat_enterprise_linux_8:idm:client/python-jwcrypto",
						"red_hat_enterprise_linux_9:python-jwcrypto"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"details": "Moderate",
					"product_ids": [
						"red_hat_ansible_automation_platform_2:automation-controller",
						"red_hat_enterprise_linux_7:python-jwcrypto",
						"red_hat_enterprise_linux_8:idm:DL1/python-jwcrypto",
						"red_hat_enterprise_linux_8:idm:client/python-jwcrypto",
						"red_hat_enterprise_linux_9:python-jwcrypto"
					]
				}
			],
			"title": "python-jwcrypto: malicious JWE token can cause denial of service"
		}
	]
}
